source/apps/main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MainView.as_view(), name="main"),
    path('update/', views.HeaderUpdateAjax.as_view(), name="main"),
]

source/apps/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('signin/', views.SignInView.as_view(), name="signin"),
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile/<str:user>/', views.ProfileView.as_view(), name="profile"),
    path('dialogs/', views.DialogsView.as_view(), name="dialogs"),
    path('dialogs/<int:page>/', views.DialogsView.as_view(), name="dialogs"),
    path('dialog/<int:dialog>/', views.MessageView.as_view(), name="dialog_detail"),
    path('dialog/<int:dialog>/<int:page>/', views.MessageView.as_view(), name="dialog_detail"),
    path('friends/', views.FriendsView.as_view(), name='friends'),
    path('friends/<int:page>/', views.FriendsView.as_view(), name='friends'),
    path('statistic/', views.StatisticView.as_view(), name='statistic'),
    path('achievement/', views.AchievementView.as_view(), name='achievement'),
    path('logout/', views.LogoutView.as_view(), name="logout"),
]

source/config/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include(('apps.main.urls', 'main'), namespace="main")),
    path('', include(('apps.user.urls', 'user'), namespace="user")),
    path('game/', include(('apps.game.urls', 'game'), namespace="game")),
    path('admin/', admin.site.urls),
]

source/apps/main/models.py
from django.db import models

# Create your models here.

source/apps/main/views/ajax.py
from django.apps import apps
from django.http import JsonResponse
from django.views import View

from ...user.models import user
from ...utils.templatetags import short_format


class HeaderUpdateAjax(View):
    """
    Обновляет header
    """
    statistic_model = apps.get_model('user', 'StatisticModel')
    dialog_model = apps.get_model('user', 'DialogModel')
    user_model = apps.get_model('user', 'UserModel')

    def get(self, request):
        """
        Метод получает данные о пользователя из базы и возвращает JSON-ответ
        """
        u_id = request.user.id
        statistic_data = self.statistic_model.get_statistics(self, u_id)

        icon = 'message.png'
        if self.dialog_model.is_read(self, u_id):
            icon = 'message_unread.png'

        data = {
            'budget': short_format.short_format(statistic_data.budget),
            'income': short_format.short_format(statistic_data.income),
            'reputation': statistic_data.reputation,
            'icon': icon
        }

        # Кадое обновление страницы вызвавет обновление статуса
        user.status_update(u_id)



        return JsonResponse(data)

source/templates/main/main.htm
{% extends "base.htm" %}
{% load static %}

{% block style %}main.css{% endblock %}
{% block header %}
    <!-- Скрываем шапку, если пользователь ещё не вошёл в игру -->
{% endblock %}
{% block content %}
    {% if user.is_authenticated is False %}
        <div class="group-logo">
            <h1>Онлайн-игра Землекоп!</h1>
            <p>Копай шахты, добывай ресурсы - стань самым богатым шахтёром в игре!</p>
            <img src="{% static 'images/logo.png' %}" alt="Логотип онлайн-игры Землекоп" class="logo">
        </div>
        <div class="group-button">
                <a href="{% url 'user:signin' %}" class="default-button">Войти</a>
                <a href="{% url 'user:signup' %}" class="default-button">Регистрация</a>
        </div>
    {%  else %}
        {% include "game/game.htm" %}
    {% endif %}
{% endblock %}