source/apps/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('signin/', views.SignInView.as_view(), name="signin"),
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile/<str:user>/', views.ProfileView.as_view(), name="profile"),
    path('dialogs/', views.DialogsView.as_view(), name="dialogs"),
    path('dialogs/<int:page>/', views.DialogsView.as_view(), name="dialogs"),
    path('dialog/<int:dialog>/', views.MessageView.as_view(), name="dialog_detail"),
    path('dialog/<int:dialog>/<int:page>/', views.MessageView.as_view(), name="dialog_detail"),
    path('friends/', views.FriendsView.as_view(), name='friends'),
    path('friends/<int:page>/', views.FriendsView.as_view(), name='friends'),
    path('statistic/', views.StatisticView.as_view(), name='statistic'),
    path('achievement/', views.AchievementView.as_view(), name='achievement'),
    path('logout/', views.LogoutView.as_view(), name="logout"),
]

source/config/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include(('apps.main.urls', 'main'), namespace="main")),
    path('', include(('apps.user.urls', 'user'), namespace="user")),
    path('game/', include(('apps.game.urls', 'game'), namespace="game")),
    path('admin/', admin.site.urls),
]

source/templates/base.htm
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!--<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'js/user.js' %}"></script>
    <script src="{% static 'js/game.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static '/css/base.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static '/css/' %}{% block style %}{% endblock %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="minimum-scale=1.0, width=device-width, maximum-scale=1.0">
    <title>
        {{ title }}
    </title>
</head>
<body class="container">
    {% block header %}
        <header>
                {% include "header.htm" %}
        </header>
    {% endblock %}
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        {% include "footer.htm" %}
    </footer>
</body>
</html>

source/templates/footer.htm
<div>Создано digger.mobi</div>
<div>2019-2020 г.</div>

source/templates/header.htm
{% load static %}
{% load short_format %}
<script>

    async function update()
    {
        $.getJSON('/update/', function (data)
        {
            $('#ajax_budget').html(data.budget);
            $('#ajax_income').html(data.income);
            $('#ajax_message').html(data.message);
            $('#message').attr('src', "{% static '/images/messages/' %}" + data.icon);
        }) ;
    }

    update();
    setInterval('update()', 3000);
</script>
<div class="info">
        <div class="infogroup"><div class="budget"></div><div id="ajax_budget"></div></div>
        <div class="infogroup"><div class="income"></div><div id="ajax_income"></div></div>
</div>
<div class="title">
    <h1>{{ title }}</h1>
</div>
<div class="message">
    <a href="{% url 'user:dialogs' %}"><img src="{% static '/images/messages/message.png' %}" id="message"></a>
</div>