source/apps/game/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.GameView.as_view(), name="game"),
    path('rating/', views.RatingView.as_view(), name="rating"),
    path('rating/<int:page>/', views.RatingView.as_view(), name="rating"),
    path('rating/budget/', views.RatingBudgetView.as_view(), name="rating_budget"),
    path('rating/budget/<int:page>/', views.RatingBudgetView.as_view(), name="rating_budget"),
    path('rating/income/', views.RatingIncomeView.as_view(), name="rating_income"),
    path('rating/income/<int:page>/', views.RatingIncomeView.as_view(), name="rating_income"),
    path('rating/reputation/', views.RatingReputationView.as_view(), name="rating_reputation"),
    path('rating/reputation/<int:page>/', views.RatingReputationView.as_view(), name="rating_reputation"),
    path('mine/', views.MineView.as_view(), name="mine"),
    path('mine/page/<int:page>/', views.MineView.as_view(), name="mine"),
    path('mine/<int:mine_id>/', views.BrigadeView.as_view(), name="brigade"),
    path('mine/<int:mine_id>/<int:page>/', views.BrigadeView.as_view(), name="brigade"),
]

source/apps/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('signin/', views.SignInView.as_view(), name="signin"),
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile/<str:user>/', views.ProfileView.as_view(), name="profile"),
    path('dialogs/', views.DialogsView.as_view(), name="dialogs"),
    path('dialogs/<int:page>/', views.DialogsView.as_view(), name="dialogs"),
    path('dialog/<int:dialog>/', views.MessageView.as_view(), name="dialog_detail"),
    path('dialog/<int:dialog>/<int:page>/', views.MessageView.as_view(), name="dialog_detail"),
    path('friends/', views.FriendsView.as_view(), name='friends'),
    path('friends/<int:page>/', views.FriendsView.as_view(), name='friends'),
    path('statistic/', views.StatisticView.as_view(), name='statistic'),
    path('achievement/', views.AchievementView.as_view(), name='achievement'),
    path('logout/', views.LogoutView.as_view(), name="logout"),
]

source/config/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include(('apps.main.urls', 'main'), namespace="main")),
    path('', include(('apps.user.urls', 'user'), namespace="user")),
    path('game/', include(('apps.game.urls', 'game'), namespace="game")),
    path('admin/', admin.site.urls),
]

source/apps/user/forms/dialog_detail.py
from django import forms


class DialogDetailForm(forms.Form):
    """
    Форма отправки личных сообщений
    fields: список полей, которые будут переданы

    message: сообщение
    password: пароль пользователя
    """
    class Meta:
        fields = ('message', 'addressee',)

    message = forms.CharField(label='', max_length=1024, widget=forms.Textarea)
    addressee = forms.CharField(widget=forms.HiddenInput())

source/apps/user/forms/signin.py
from django import forms


class SignInForm(forms.Form):
    """
    Форма авторизации на сайте
    fields: список полей, которые будут переданы

    username: логин пользователя
    password: пароль пользователя
    """
    class Meta:
        fields = ('username', 'password')

    username = forms.CharField(label='', max_length=16, widget=forms.TextInput(attrs={'placeholder': 'Логин'}))
    password = forms.CharField(label='', max_length=32, widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))

source/apps/user/forms/signup.py
from django import forms
from django.contrib.auth.hashers import make_password
from django.forms import ModelForm

from ..models.user import UserModel


class SignUpForm(ModelForm):
    class Meta:
        model = UserModel
        fields = ('username', 'password')

    username = forms.CharField(label='', max_length=16, widget=forms.TextInput(attrs={'placeholder': 'Логин'}))
    password = forms.CharField(label='', max_length=32, widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))

source/apps/user/views/achievements.py
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from ..models import achievement


class AchievementView(TemplateView):
    """
    Вывод списка диалогов
    """

    template_name = "user/achievement.htm"
    model = apps.get_model('user', 'AchievementModel')

    @method_decorator(login_required(login_url='/signin/'))
    #@method_decorator(cache_page(60 * 5), name='dispatch')
    def get(self, request, *args, **kwargs):
        """
        Действия при открытии страницы
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        context = super(AchievementView, self).get_context_data(**kwargs)

        context['title'] = 'Достижения'
        achievement.update(request.user.id)
        context['achievements'] = achievement.get(request.user.id)
        return render(request, self.template_name, context)

source/apps/user/views/dialog.py
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView


class DialogsView(TemplateView):
    """
    Вывод списка диалогов
    """

    template_name = "user/dialog.htm"
    model = apps.get_model('user', 'DialogModel')

    @method_decorator(login_required(login_url='/signin/'))
    #@method_decorator(cache_page(60 * 5), name='dispatch')
    def get(self, request, *args, **kwargs):
        """
        Действия при открытии страницы
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        context = super(DialogsView, self).get_context_data(**kwargs)

        context['title'] = 'Личные сообщения'

        context['messages'] = self.model.get_list(self, request.user.id)

        page = self.kwargs.get('page', 1)
        paginator = Paginator(context['messages'], 5)

        context['pages'] = paginator.get_page(page)
        context['page'] = page

        # Код ниже делает так, чтобы пагинация корректно отображалась
        plusator = 3

        if page == 1 or page == paginator.num_pages:
            plusator = 5
        if page == 2 or page == paginator.num_pages - 1:
            plusator = 4
        if page == 3 or page == paginator.num_pages - 2:
            plusator = 3

        context['plusator'] = plusator
        context['minusator'] = -plusator

        return render(request, self.template_name, context)

source/apps/user/views/friends.py
import time
from pprint import pprint

from django.apps import apps
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from ...user import services


class FriendsView(TemplateView):
    """
    Вывод списка диалогов
    """

    template_name = "user/friends.htm"
    model = apps.get_model('user', 'FriendsModel')

    @method_decorator(login_required(login_url='/signin/'))
    #@method_decorator(cache_page(60 * 5), name='dispatch')
    def get(self, request, *args, **kwargs):
        """
        Действия при открытии страницы
        """

        u_id = request.user.id

        context = super(FriendsView, self).get_context_data(**kwargs)

        context['title'] = 'Друзья'

        context['friends'] = self.model.get_list(self, u_id)
        context['friends_in'] = self.model.get_request_in(self, u_id)
        context['friends_out'] = self.model.get_request_out(self, u_id)

        page = self.kwargs.get('page', 1)
        paginator = Paginator([], 5)

        #context['pages'] = paginator.get_page(page)
        #context['page'] = page

        # Код ниже делает так, чтобы пагинация корректно отображалась
        plusator = 3

        if page == 1 or page == paginator.num_pages:
            plusator = 5
        if page == 2 or page == paginator.num_pages - 1:
            plusator = 4
        if page == 3 or page == paginator.num_pages - 2:
            plusator = 3

        context['plusator'] = plusator
        context['minusator'] = -plusator

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """
        Отправка заявки в друзья
        """
        action = request.POST['action']
        friend = request.POST['friend_id']
        if action == 'request':
            services.RequestFriend.execute({'from_': request.user.id,
                                            'to': friend})
        if action == 'cancel':
            result = self.model.request_cancel(self, request.user.id, friend)
            if result == None:
                messages.error(request, 'Заявка уже не существует!')

        if action == 'accept':
            result = self.model.request_accept(self, request.user.id, friend)
            if result is None:
                messages.error(request, 'Заявка уже не существует!')

        if action == 'delete':
            result = self.model.friend_delete(self, request.user.id, friend)
            if result is None:
                messages.error(request, 'Заявка уже не существует!')


        return HttpResponseRedirect('/friends/')

source/apps/user/views/logout.py
from django.contrib.auth import logout
from django.views.generic import RedirectView


class LogoutView(RedirectView):
    """
    Выход
    """
    url = '/'

    def get(self, request, *args, **kwargs):
        """
        Действия при нажатии кнопки "Выйти"
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

source/apps/user/views/message.py
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from ...utils import utils
from ...user import services
from ..forms import DialogDetailForm


class MessageView(TemplateView):
    """
    Обработка страницы авторизации на сайте
    """

    template_name = "user/message.htm"
    model = apps.get_model('user', 'MessageModel')
    user_model = apps.get_model('user', 'UserModel')

    @method_decorator(login_required(login_url='/signin/'))
    #@method_decorator(cache_page(60 * 5), name='dispatch')
    def get(self, request, *args, **kwargs):
        """
        Действия при открытии страницы
        """
        context = super(MessageView, self).get_context_data(**kwargs)
        context['title'] = 'Личные сообщения'

        # Скрытое поле, показывающее, кому будет отправлено сообщение
        dialog = self.kwargs.get('dialog', None)
        context['form'] = DialogDetailForm(initial={'addressee': dialog})

        # Для формирования логина и id, если диалогов не было ранее
        context['userinfo'] = self.user_model.get_userinfo(self, dialog)

        # Пагинация на странице
        data = self.model.get_messages(self, request.user.id, dialog)
        context['pages'] = utils.paginator(self, data, 5)

        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url='/signin/'))
    def post(self, request, *args, **kwargs):
        form = DialogDetailForm(request.POST)

        if form.is_valid():
            addressee = request.POST.get('addressee')
            message = request.POST.get('message')

            # Отправляем сообщение другому пользователю
            self.model.send(self, request.user.id, addressee, message)

            services.CreateAction.execute(
                {
                    'from_': request.user.id,
                    'to': addressee,
                    'action': 'Вам пришло <a href="/dialogs/">письмо</a> от игрока <a href="/profile/{player}/">{player}</a>!',
                }
            )

        dialog = self.kwargs.get('dialog', None)
        return HttpResponseRedirect('/dialog/%s/' % dialog)

source/apps/user/views/profile.py
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from ...user.models import user, friend

class ProfileView(TemplateView):
    """
    Вывод профиля пользователя
    """

    template_name = "user/profile.htm"

    friend_model = apps.get_model('user', 'FriendsModel')
    rating_model = apps.get_model('game', 'RatingModel')

    @method_decorator(login_required(login_url='/signin/'))
    def get(self, request, *args, **kwargs):
        """
        Действия при открытии страницы
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        context = super(ProfileView, self).get_context_data(**kwargs)

        context['title'] = 'Профиль'

        u_id = request.user.id
        page = user.get_id(self.kwargs.get('user', None))

        # Проверить, является ли пользователь владельцем аккаунта
        id = u_id if page is None else page

        context['player'] = user.get_info(id)
        context['friend'] = friend.get_friend_status(u_id, context['player'].id)

        return render(request, self.template_name, context)

source/apps/user/views/signin.py
from django.apps import apps
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from ..forms.signin import SignInForm


class SignInView(TemplateView):
    """
    Обработка страницы авторизации на сайте
    """

    template_name = "user/signin.htm"
    statistic_model = apps.get_model('user', 'StatisticModel')

    #@method_decorator(cache_page(60 * 5), name='dispatch')
    def get(self, request, *args, **kwargs):
        """
        Действия при открытии страницы
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        context = super(SignInView, self).get_context_data(**kwargs)

        form = SignInForm()
        context['form'] = form

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = SignInForm(request.POST)

        # Проверка на корректность ввода логина и пароля
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is None:
                messages.error(request, 'Неправильный логин или пароль!')
            else:
                login(request, user)
                return HttpResponseRedirect('/')

        return HttpResponseRedirect('/signin/')

source/apps/user/views/signup.py
from django.apps import apps
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from ..forms.signup import SignUpForm


class SignUpView(TemplateView):
    """
    Обработка страницы регистрации на сайте
    """

    template_name = "user/signup.htm"
    user_model = apps.get_model('user', 'UserModel')
    statistic_model = apps.get_model('user', 'StatisticModel')

    def get(self, request, *args, **kwargs):
        """
        Действия при открытии страницы
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        context = super(SignUpView, self).get_context_data(**kwargs)
        context['form'] = SignUpForm()
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        """
        Действия при отправка запроса на регистрацию
        :param request:
        :return:
        """
        form = SignUpForm(request.POST)

        # Проверим валидность формы и в случае успеха отправим на страницу входа В противном случае покажем сообщение
        # об ошибке
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            self.user_model.create(self, username, password)

            return HttpResponseRedirect('/signin/')
        else:
            messages.error(request, 'Логин уже занят!')
            return HttpResponseRedirect('/signup/')

        return HttpResponseRedirect('/')

source/templates/user/achievement.htm
{% extends "base.htm" %}
{% load static %}

{% block style %}user.css{% endblock %}

{% block content %}
    <h2>Прогресс достижений</h2>

    {% for achievement in achievements %}
        <div class="achievement">
            <div class="left">
                <img src="{% static 'images/achievements/' %}{{ achievement.image }}">
                <div>
                    <p><b>{{ achievement.name }}</b>, {{ achievement.level }} ур.</p>
                    <p>{{ achievement.description }}</p>
                </div>
            </div>
            <div class="right">
                <div>
                    <p><img src="{% static 'images/progress.png' %}">{{ achievement.progress|floatformat:1 }}%</p>
                    <p><img src="{% static 'images/diamond.png' %}">{{ achievement.reward}}</p>
                </div>
            </div>
        </div>
    {% endfor %}
    {% include 'utils/game_buttons.htm' %}
{% endblock %}

source/templates/user/dialog.htm
{% extends "base.htm" %}
{% load static %}

{% block style %}user.css{% endblock %}

{% block content %}
    <h2>Список диалогов</h2>
    {% if pages.0.dialog.id %}
        {% for page in pages %}
           <div class="msg">
               <a href="{% url 'user:dialog_detail' page.dialog.id %}">
                   <div class="message-group">
                       <img src="{% static '/images/messages/' %}{{ page.icon }}">
                       <div class="author">{{ page.dialog }}</div>
                   </div>
                   <div class="time">{{ page.time|date:"d.m.y H:i" }}</div>
               </a>
           </div>
        {% endfor %}
    {% include 'utils/pagenator.htm' with app='user:dialogs' param1=pages %}
    {% else %}
        <p>Диалогов не найдено.</p>
    {% endif %}
    {% include 'utils/game_buttons.htm' %}
{% endblock %}

source/templates/user/friends.htm
{% extends "base.htm" %}
{% load static %}

{% block style %}user.css{% endblock %}

{% block content %}
    {% if messages %}
        <p class="error">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </p>
   {% endif %}
    <h2>Список друзей</h2>
    {% for friend in friends %}
        <div class="friend">
            <div>
                <img src="{% static 'images/avatars/default.png' %}">
                <a href="{% url 'user:profile' friend.username.id %}">{{ friend.username }}</a>
            </div>
            <div>
                <a href="#" onclick="friend_request('{{ csrf_token }}', {{ friend.id }}, 'delete')" class="medium-button">&#10005;</a>
            </div>
        </div>
    {% empty %}
        <p>У вас ещё нет друзей.</p>
    {% endfor %}
    {% for friend_in in friends_in %}
        {% ifchanged %}
            <h2>Входящие заявки</h2>
        {% endifchanged %}
        <div class="friend">
            <div>
                <img src="{% static 'images/avatars/default.png' %}">
                <a href="{% url 'user:profile' friend_in.user.id %}">{{ friend_in.user }}</a>
            </div>
            <div>
                <a href="#" onclick="friend_request('{{ csrf_token }}', {{ friend_in.user.id }}, 'accept')" class="medium-button">&#10003;</a>
                <a href="#" onclick="friend_request('{{ csrf_token }}', {{ friend_in.user.id }}, 'cancel')" class="medium-button">&#10005;</a>
            </div>
        </div>
    {% endfor %}
    {% for friend_out in friends_out %}
        {% ifchanged %}
            <h2>Исходящие заявки</h2>
        {% endifchanged %}
        <div class="friend">
            <div>
                <img src="{% static 'images/avatars/default.png' %}">
                <a href="{% url 'user:profile' friend_out.friend.id %}">{{ friend_out.friend }}</a>
            </div>
            <div>
                <a href="#" onclick="friend_request('{{ csrf_token }}', {{ friend_out.friend.id }}, 'cancel')" class="medium-button">&#10005;</a>
            </div>
        </div>
    {% endfor %}
    {% include 'utils/game_buttons.htm' %}
{% endblock %}

source/templates/user/message.htm
{% extends "base.htm" %}
{% load static %}

{% block style %}user.css{% endblock %}

{% block content %}

    {% if dialog == user.id %}
        <p>Вы не можете писать сообщение самому себе!</p>
    {% else %}
        <h2>Диалог с <a href="{% url 'user:profile' userinfo.id %}">{{ userinfo.username }}</a></h2>

        <form action="" method="POST">
            {% csrf_token %}
            {{ form.message }}
            {{ form.addressee }}
            <input type="submit" value="Отправить">
        </form>
        <hr>
        {% if pages %}
            {% for page in pages.data %}
               <div class="dialog">
                   <div class="title">
                       <div class="author">
                           {% if page.author.id == user.id %}
                                <b>Вы</b>
                           {% else %}
                                <b>{{ page.author }}</b>
                           {% endif %}
                       </div>
                       <div class="time">{{ page.time|timesince }} назад</div>
                   </div>
                   <div class="text">{{ page.message }}</div>
               </div>
            {% endfor %}
            {% include 'utils/pagenator.htm' with app='user:dialog_detail' param2=dialog param1=pages %}
        {% else %}
            <p>Вы ранее не переписывались друг с другом.</p>
        {% endif %}
    {% endif %}
    <a href='{% url 'user:dialogs' %}' class="default-button">Диалоги</a>
    {% include 'utils/game_buttons.htm' %}
{% endblock %}

source/templates/user/profile.htm
{% extends "base.htm" %}
{% load static %}
{% load short_format %}

{% block style %}user.css{% endblock %}

{% block content %}
    {% if auth %}
        <h2>Ваш профиль</h2>
    {% else %}
        <h2>Профиль игрока {{ player }}</h2>
    {% endif %}
    <div class="avatar">
        <img src="{% static 'images/avatars/default.png' %}">
    </div>
    <div class="username">{{ player }}</div>
    {% if player.online.online %}
        <div class="status">Сейчас&nbsp;<div class="online">онлайн</div>.</div>
    {% else %}
        <div class="status">Сейчас&nbsp;<div class="offline">оффлайн</div>.</div>
        <div class="status">Был в сети {{ player.online.text|timesince }} назад.</div>
    {% endif %}
    <div class="stats">
        <div class="stat">
            <img src="{% static 'images/income.png' %}">{{ player.statistics.income|short_format }}
        </div>
        <div class="stat">
            <img src="{% static 'images/budget.png' %}">{{ player.statistics.budget|short_format }}
        </div>
        <div class="stat">
            <img src="{% static 'images/rating.png' %}">{{ player.rating }}
        </div>
        <div class="stat">
            <img src="{% static 'images/reputation.png' %}">{{ player.statistics.reputation|short_format }} <div>{{ player.statistics.future_reputation|short_format }}</div>
        </div>
        {% if player.id == request.user.id %}
            <div class="stat">
                <img src="{% static 'images/diamond.png' %}">{{ player.diamond }}
            </div>
        {% endif %}
    </div>
    {% if player.rewards %}
        <h2>Награды</h2>
        <div class="rewards">
        {% for reward in player.rewards %}
            <div class="reward">
                <img src="{% static 'images/rewards/' %}{{ reward.file }}">
            </div>
        {% endfor %}
        </div>
    {% endif %}

    {% if player.id == request.user.id %}
        <a href="{% url 'user:friends' %}" class="default-button">Друзья</a>
        <a href="{% url 'user:dialogs' %}" class="default-button">Личные сообщения</a>
        <a href="{% url 'user:statistic' %}" class="default-button">Статистика</a>
        <a href="{% url 'user:achievement' %}" class="default-button">Достижения</a>
        <a href="{% url 'game:game' %}" class="default-button">Настройки</a>
        <a href="{% url 'user:logout' %}" class="default-button">Выход</a>
    {% else %}
        <a href="{% url 'user:dialog_detail' player.id %}" class="default-button">Написать сообщение</a>
        <!-- TODO: шаблон нуждается в переработке -->
        {{ friend.username }}
        {% if friend.u_from is None and friend.to_from is None %}
            <a href="#" onclick="friend_request('{{ csrf_token }}', {{ player.id }}, 'request')" class="default-button">Добавить в друзья</a>
        {% endif %}
        {% if friend.status == True %}
            <a href="#" onclick="friend_request('{{ csrf_token }}', {{ player.id }}, 'delete')" class="default-button">Удалить из друзей</a>
        {% endif %}
        {% if friend.u_from.id == request.user.id and friend.status == False %}
             <a href="#" onclick="friend_request('{{ csrf_token }}', {{ player.id }}, 'cancel')" class="default-button">Отменить заявку в друзья</a>
        {% elif friend.u_to.id == request.user.id and friend.status == False %}
            <a href="#" onclick="friend_request('{{ csrf_token }}', {{ player.id }}, 'accept')" class="default-button">Принять заявку в друзья</a>
        {% endif %}
        <!-- end -->
        <a href="{% url 'game:game' %}" class="default-button">Пригласить в профсоюз</a>
        <hr>
        <a href="{% url 'game:game' %}" class="default-button">В чёрный список</a>
        <a href="{% url 'game:game' %}" class="default-button">Сообщить о нарушении</a>
    {% endif %}
    <hr>
    <a href="{% url 'game:game' %}" class="default-button">В Меню</a>
{% endblock %}

source/templates/user/signin.htm
{% extends "base.htm" %}
{% load static %}

{% block style %}user.css{% endblock %}
{% block title %}Авторизация{% endblock %}


{% block content %}
    <h1>Авторизация</h1>
    <p>Введите данные в поля ниже, чтобы получить возможность играть в игру.</p>
    {% if messages %}
        <p class="error">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </p>
   {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.username }}
        {{ form.password }}
        <input type="submit" name="submit" value="Отправить">
    </form>
    <hr>

        <a href="{% url 'user:signin' %}" class="default-button">Забыли пароль?</a>
        <a href="/" class="default-button">На главную</a>


{% endblock %}

source/templates/user/signup.htm
{% extends "base.htm" %}
{% load static %}

{% block style %}user.css{% endblock %}
{% block title %}Регистрация{% endblock %}


{% block content %}
    <h1>Регистрация</h1>
    <p>Введите данные в поля ниже, чтобы получить возможность играть в игру.</p>
    {% if messages %}

        <p class="error">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </p>
   {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.username }}
        {{ form.password }}
        <input type="submit" name="submit" value="Отправить">
    </form>
    <hr>
    <a href="/" class="default-button">На главную</a>

{% endblock %}

source/templates/user/statistics.htm
{% extends "base.htm" %}
{% load static %}
{% load humanize %}
{% load short_format %}


{% block style %}user.css{% endblock %}

{% block content %}
    <h2>Общее</h2>
    <div class="statistic">
        <div>Дата регистрации</div><div>{{ player.signup_date }}</div>
    </div>
    <div class="statistic">
        <div>Время в игре</div><div>{{ player.signup_date|timesince }}</div>
    </div>
    <div class="statistic">
        <div>Время в онлайне</div><div>{{ player.time_online|timesince }}</div>
    </div>
    <div class="statistic">
        <div>Время 100% эффективности</div><div>{{ player.efficiency_time }}</div>
    </div>
    <div class="statistic">
        <div>Время спада эффективности</div><div>{{ player.efficiency_recession }}</div>
    </div>
    {% if worker is False %}
        <p class="tips">Рекомендуем <a href="#">нанять</a> аналитика для более подробной информации о Вашей компании!</p>
    {% endif %}
    <h2>Доход</h2>
    <div class="statistic">
        <div>Текущий доход</div><div>{{ player.income|short_format }}</div>
    </div>
    {% if worker %}
        <div class="statistic">
            <div>Максимальный доход</div><div>{{ player.income|short_format }}</div>
        </div>
    {% endif %}

    <h2>Бюджет</h2>
    <div class="statistic">
        <div>Текущий бюджет</div><div>{{ player.budget|short_format }}</div>
    </div>
    {% if worker %}
        <div class="statistic">
            <div>Общий бюджет</div><div>{{ player.budget_total|short_format }}</div>
        </div>
        <div class="statistic">
            <div>Максимальный бюджет</div><div>{{ player.budget|short_format }}</div>
        </div>
        <div class="statistic">
            <div>Бюджет через минуту</div><div>{{ player.budget1m|short_format }}</div>
        </div>
        <div class="statistic">
            <div>Бюджет через час</div><div>{{ player.budget1h|short_format }}</div>
        </div>
        <div class="statistic">
            <div>Бюджет через сутки</div><div>{{ player.budget1d|short_format }}</div>
        </div>
    {% endif %}



    <h2>Репутация</h2>
    <div class="statistic">
        <div>Текущая репутация</div><div>{{ player.future_reputation|short_format }}</div>
    </div>
    {% if worker %}
        <div class="statistic">
            <div>Общая репутация</div><div>{{ player.reputation|short_format }}</div>
        </div>
        <div class="statistic">
            <div>Прирост репутации в минуту</div><div>{{ player.reputation_income|short_format }}</div>
        </div>
        <div class="statistic">
            <div>Репутация через минуту</div><div>{{ player.reputation1m|short_format }}</div>
        </div>
        <div class="statistic">
            <div>Репутация через час</div><div>{{ player.reputation1h|short_format }}</div>
        </div>
        <div class="statistic">
            <div>Репутация через сутки</div><div>{{ player.reputation1d|short_format }}</div>
        </div>
    {% endif %}
    {% include 'utils/game_buttons.htm' %}
{% endblock %}