source/apps/game/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.GameView.as_view(), name="game"),
    path('rating/', views.RatingView.as_view(), name="rating"),
    path('rating/<int:page>/', views.RatingView.as_view(), name="rating"),
    path('rating/budget/', views.RatingBudgetView.as_view(), name="rating_budget"),
    path('rating/budget/<int:page>/', views.RatingBudgetView.as_view(), name="rating_budget"),
    path('rating/income/', views.RatingIncomeView.as_view(), name="rating_income"),
    path('rating/income/<int:page>/', views.RatingIncomeView.as_view(), name="rating_income"),
    path('rating/reputation/', views.RatingReputationView.as_view(), name="rating_reputation"),
    path('rating/reputation/<int:page>/', views.RatingReputationView.as_view(), name="rating_reputation"),
    path('mine/', views.MineView.as_view(), name="mine"),
    path('mine/page/<int:page>/', views.MineView.as_view(), name="mine"),
    path('mine/<int:mine_id>/', views.BrigadeView.as_view(), name="brigade"),
    path('mine/<int:mine_id>/<int:page>/', views.BrigadeView.as_view(), name="brigade"),
]

source/apps/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('signin/', views.SignInView.as_view(), name="signin"),
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile/<str:user>/', views.ProfileView.as_view(), name="profile"),
    path('dialogs/', views.DialogsView.as_view(), name="dialogs"),
    path('dialogs/<int:page>/', views.DialogsView.as_view(), name="dialogs"),
    path('dialog/<int:dialog>/', views.MessageView.as_view(), name="dialog_detail"),
    path('dialog/<int:dialog>/<int:page>/', views.MessageView.as_view(), name="dialog_detail"),
    path('friends/', views.FriendsView.as_view(), name='friends'),
    path('friends/<int:page>/', views.FriendsView.as_view(), name='friends'),
    path('statistic/', views.StatisticView.as_view(), name='statistic'),
    path('achievement/', views.AchievementView.as_view(), name='achievement'),
    path('logout/', views.LogoutView.as_view(), name="logout"),
]

source/config/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include(('apps.main.urls', 'main'), namespace="main")),
    path('', include(('apps.user.urls', 'user'), namespace="user")),
    path('game/', include(('apps.game.urls', 'game'), namespace="game")),
    path('admin/', admin.site.urls),
]

source/apps/game/models/brigade.py
from decimal import Decimal

from django.apps import apps
from django.db import models

from ...game.models import MineModel
from ...user.models import UserModel


class BrigadeModel(models.Model):
    """
    Бригады

    Fields:
        user: ссылка на пользователя
        mine: привязка бригады к шахте
        brigade_id: id бригады

        icon: иконка брикады
        worker: количество работников
        recruit_cost: стоимость найма бригады
        recruit_worker_cost: стоимость найма сотрудника
        recruit_cost_m: множитель найма бригады
        recruit_worker_cost_m: множитель найма работника
        income: доход
        income_m: множитель дохода
    """

    class Meta:
        db_table = "digger_brigades"

    user = models.ForeignKey(UserModel, related_name='brigade', default=None, null=True, on_delete=models.CASCADE)
    mine_id = models.IntegerField(default=1)
    brigade_id = models.IntegerField(default=1)

    icon = models.CharField(max_length=256, default='default.png')
    worker = models.IntegerField(default=1)
    recruit_cost = models.DecimalField(max_digits=1000, decimal_places=0, default=1)
    recruit_worker_cost = models.DecimalField(max_digits=1000, decimal_places=0, default=1)
    recruit_worker_cost_base = models.DecimalField(max_digits=1000, decimal_places=0, default=10)
    recruit_cost_multiple = models.DecimalField(max_digits=1000, decimal_places=0, default=10)
    recruit_worker_cost_multiple = models.DecimalField(max_digits=1000, decimal_places=0, default=10)
    income = models.DecimalField(max_digits=1000, decimal_places=0, default=1)
    income_base = models.DecimalField(max_digits=1000, decimal_places=0, default=1)
    income_multiple = models.DecimalField(max_digits=1000, decimal_places=0, default=1)


def get_last_price(u_id, mine_id):
    """
    Вернуть последнюю цену для формирования бригады
    Args:
        u_id: id пользователя
        mine_id: id шахты
    Returns:
        Стоимость следующего строительства шахты
    """
    data = BrigadeModel.objects.filter(user_id=u_id, mine_id=mine_id).last()

    if data:
        return data.recruit_cost
    else:
        return 10 * int(mine_id)


def get(u_id, mine_id):
    """
    Вернуть список бригад внутри одной шахты
    Args:
        u_id: id пользователя
        mine_id: id шахты

    Returns:
        Список шахт
    """
    data = BrigadeModel.objects.filter(user_id=u_id, mine_id=mine_id).order_by('-id').values()

    return data


def create(u_id, mine_id):
    """
    Сформировать бригаду
    Args:
        u_id: id пользователя
        mine_id: id шахты

    Returns:
        Ничего, если хватает средств и False, если их не хватает
    """
    mine_id = int(mine_id)
    brigade_data = BrigadeModel.objects.filter(user_id=u_id, mine_id=mine_id).last()
    user_data = apps.get_model('user', 'StatisticModel').objects.get(user_id=u_id)


    if brigade_data:
        brigade_id = brigade_data.brigade_id + 1
        recruit_cost = Decimal(brigade_data.recruit_cost)
        recruit_cost_multiple = Decimal(brigade_data.recruit_cost_multiple)
        recruit_worker_cost = Decimal(brigade_data.recruit_worker_cost)
        recruit_worker_cost_multiple = Decimal(brigade_data.recruit_worker_cost_multiple)
        income_multiple = Decimal(brigade_data.income_multiple)
    else:
        brigade_id = 1
        recruit_cost = 10 * mine_id
        recruit_cost_multiple = 10
        recruit_worker_cost = mine_id
        recruit_worker_cost_multiple = 10
        income_multiple = 1

    if user_data.budget >= recruit_cost:
        # Определяет цену формирования новой шахты
        new_recruit_cost = recruit_cost * recruit_cost_multiple
        # Определяет цену найма сотрудника
        new_recruit_worker_cost = recruit_worker_cost * recruit_worker_cost_multiple
        # Определяет доход бригады
        new_income = brigade_id * mine_id * income_multiple


        model = BrigadeModel(
            user_id=u_id,
            mine_id=mine_id,
            brigade_id=brigade_id,
            recruit_cost=new_recruit_cost,
            recruit_worker_cost=new_recruit_worker_cost,
            recruit_worker_cost_base=new_recruit_worker_cost,
            income=new_income,
            income_base=new_income,
        )

        model.save()

        user_data.budget -= recruit_cost
        user_data.save()


def upgrade(u_id, mine_id, brigade_id, count):
    """
    Улучшить бригаду (добавить сотрудника)
    Args:
        u_id: id пользователя
        mine_id: id шахты
        brigade_id: id бригады
        count: количество улучшений

    Returns:
        Ничего
    """
    count = int(count)

    brigade_data = BrigadeModel.objects.filter(user_id=u_id, mine_id=mine_id, brigade_id=brigade_id).last()
    user_data = apps.get_model('user', 'StatisticModel').objects.get(user_id=u_id)

    if brigade_data:
        recruit_worker_cost_base = Decimal(brigade_data.recruit_worker_cost_base) * count
        recruit_worker_cost = Decimal(brigade_data.recruit_worker_cost) * count
        income = Decimal(brigade_data.income)
        income_base = Decimal(brigade_data.income_base) * count
        worker = brigade_data.worker

        if user_data.budget >= recruit_worker_cost:
            # Определяет стоимость найма следующего сотрудника
            new_recruit_worker_cost = recruit_worker_cost + recruit_worker_cost_base
            # Определяет доход следующей бригады
            new_income = income + income_base
            # Определяет количество рабочиз
            worker += count

            brigade_data.recruit_worker_cost = new_recruit_worker_cost
            brigade_data.income = new_income
            brigade_data.worker = worker
            brigade_data.save()

            user_data.budget -= new_recruit_worker_cost
            user_data.save()

source/apps/game/views/brigade.py
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from ..models import brigade
from ...utils import utils, income


class BrigadeView(TemplateView):
    """
    Обработка страницы шахт
    """
    template_name = "game/brigade.htm"

    statistic_model = apps.get_model('user', 'StatisticModel')
    rating_model = apps.get_model('game', 'RatingModel')

    @method_decorator(login_required(login_url='/signin/'))
    def get(self, request, *args, **kwargs):
        """
        Действия при открытии страницы
        """
        u_id = request.user.id
        mine_id = kwargs.get('mine_id', '1')
        context = super(BrigadeView, self).get_context_data(**kwargs)
        context['title'] = 'Бригады'

        data = brigade.get(u_id, mine_id)
        context['brigades'] = utils.paginator(self, data)
        context['last_price'] = brigade.get_last_price(u_id, mine_id)

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """
        Строительство шахты
        """

        u_id = request.user.id
        action = request.POST.get('action')
        mine_id = request.POST.get('mine_id')
        brigade_id = request.POST.get('brigade_id')
        count = request.POST.get('count')

        if action == 'create':
            brigade.create(u_id, mine_id)
            income.update(u_id)

        if action == 'upgrade':
            brigade.upgrade(u_id, mine_id, brigade_id, count)


        return HttpResponseRedirect('/game/mine/')

source/apps/game/views/game.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from ...user.models import UserModel


class GameView(TemplateView):
    template_name = "game/game.htm"

    @method_decorator(login_required(login_url='/signin/'))
    # @method_decorator(cache_page(60 * 5), name='dispatch')
    def get(self, request, *args, **kwargs):
        """

        Args:
            request:
            *args:
            **kwargs:

        Returns:

        """
        context = super(GameView, self).get_context_data(**kwargs)
        context['title'] = 'Меню'

        user = UserModel.objects.get(id=request.user.id)
        context['actions'] = user.actionmodel_set.all().order_by('-time')

        return render(request, self.template_name, context)

source/apps/game/views/mine.py
from django.apps import apps
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from ..models import mine
from ...utils import utils, income


class MineView(TemplateView):
    """
    Обработка страницы шахт
    """
    template_name = "game/mine.htm"

    statistic_model = apps.get_model('user', 'StatisticModel')
    rating_model = apps.get_model('game', 'RatingModel')

    @method_decorator(login_required(login_url='/signin/'))
    def get(self, request, *args, **kwargs):
        """
        Действия при открытии страницы
        """
        u_id = request.user.id
        try:
            income.update(u_id)
        except:
            pass
        context = super(MineView, self).get_context_data(**kwargs)
        context['title'] = 'Шахты'

        data = mine.get(u_id)
        context['mines'] = utils.paginator(self, data)
        context['last_price'] = mine.get_last_price(u_id)

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """
        Строительство шахты
        """
        u_id = request.user.id
        action = request.POST['action']
        mine_id = request.POST['mine_id']
        count = request.POST['count']

        if action == 'build':
            mine.build(u_id)

        if action == 'upgrade':
            mine.upgrade(u_id, mine_id, count)

        income.update(u_id)


        return HttpResponseRedirect('/game/mine/')

source/apps/game/views/rating.py
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from ...utils import utils
from ..models import rating

class RatingView(TemplateView):
    """
    Обработка страницы общего рейтинга
    """
    template_name = "game/rating.htm"

    statistic_model = apps.get_model('user', 'StatisticModel')
    rating_model = apps.get_model('game', 'RatingModel')

    @method_decorator(login_required(login_url='/signin/'))
    # @method_decorator(cache_page(60 * 5), name='dispatch')
    def get(self, request, *args, **kwargs):
        """

        Args:
            request:
            *args:
            **kwargs:

        Returns:

        """
        context = super(RatingView, self).get_context_data(**kwargs)
        context['title'] = 'Рейтинги'


        data =  rating.get(None)
        context['pages'] = utils.paginator(self, data)

        # Предотвратить множественную переадресацию на саму себя
        if kwargs.get('page', None):
            result = render(request, self.template_name, context)
        else:
            page = utils.get_rating_page(self, None, request.user.id)
            result = redirect(reverse('game:rating', kwargs={'page': page}))

        return result


class RatingBudgetView(TemplateView):
    """
    Страница рейтинга по бюджету
    """
    template_name = "game/rating/budget.htm"

    statistic_model = apps.get_model('user', 'StatisticModel')
    rating_model = apps.get_model('game', 'RatingModel')

    @method_decorator(login_required(login_url='/signin/'))
    def get(self, request, *args, **kwargs):
        """

        Args:
            request:
            *args:
            **kwargs:

        Returns:

        """
        context = super(RatingBudgetView, self).get_context_data(**kwargs)
        context['title'] = 'Рейтинги'

        # Пагинация на странице
        context['pages'] = utils.paginator(self, rating.get('budget'))

        # Предотвратить множественную переадресацию на саму себя
        if kwargs.get('page', None):
            result = render(request, self.template_name, context)
        else:
            page = utils.get_rating_page(self, 'budget', request.user.id)
            result = redirect(reverse('game:rating_budget', kwargs={'page': page}))

        return result


class RatingIncomeView(TemplateView):
    """
    Страница рейтинга по доходу
    """
    template_name = "game/rating/income.htm"

    statistic_model = apps.get_model('user', 'StatisticModel')
    rating_model = apps.get_model('game', 'RatingModel')

    @method_decorator(login_required(login_url='/signin/'))
    def get(self, request, *args, **kwargs):
        """
        Действия при открытии страницы
        """
        context = super(RatingIncomeView, self).get_context_data(**kwargs)
        context['title'] = 'Рейтинги'

        # Пагинация на странице
        context['pages'] = utils.paginator(self, rating.get('income'))

        # Предотвратить множественную переадресацию на саму себя
        if kwargs.get('page', None):
            result = render(request, self.template_name, context)
        else:
            page = utils.get_rating_page(self, 'income', request.user.id)
            result = redirect(reverse('game:rating_income', kwargs={'page': page}))

        return result


class RatingReputationView(TemplateView):
    """
    Страница рейтинга по репутации
    """
    template_name = "game/rating/reputation.htm"

    statistic_model = apps.get_model('user', 'StatisticModel')
    rating_model = apps.get_model('game', 'RatingModel')

    @method_decorator(login_required(login_url='/signin/'))
    def get(self, request, *args, **kwargs):
        """
        Действия при открытии страницы
        """
        context = super(RatingReputationView, self).get_context_data(**kwargs)
        context['title'] = 'Рейтинги'

        # Пагинация на странице
        context['pages'] = utils.paginator(self, rating.get('reputation'))

        # Предотвратить множественную переадресацию на саму себя
        if kwargs.get('page', None):
            result = render(request, self.template_name, context)
        else:
            page = utils.get_rating_page(self, 'reputation', request.user.id)
            result = redirect(reverse('game:rating_reputation', kwargs={'page': page}))

        return result

source/templates/game/brigade.htm
{% extends "base.htm" %}
{% load static %}
{% load paginator_offset %}
{% load short_format %}
{% load multiply %}

{% block style %}game.css{% endblock %}

{% block content %}
    <h2>Список бригад</h2>
    <a href="#" onclick="brigade_create('{{ csrf_token }}','{{ mine_id }}')" class="default-button">Сформировать бригаду ({{ last_price|short_format }})</a>
    {% for brigade in brigades.data %}
        <a href="#" class="mine">
            <div class="left">
                <div>
                    <img src="{% static 'images/brigades/' %}{{ brigade.icon }}" class="icon">
                </div>
                <div>
                    <div>Бригада #{{ forloop.counter }}</div>
                    <div class="stats">
                        <img src="{% static 'images/brigades/worker.png' %}"><div>{{ brigade.worker }}</div>
                        <img src="{% static 'images/mines/income.png' %}"><div>{{ brigade.income }}</div>
                    </div>
                </div>
            </div>
            <div class="right">
                <div class="small-button" onclick="brigade_upgrade('{{ csrf_token }}', {{ mine_id }}, {{ brigade.brigade_id }}, '1')">
                    <div>1</div>
                    <div>{{ brigade.recruit_worker_cost|short_format }}</div>
                </div>
                <div class="small-button" onclick="brigade_upgrade('{{ csrf_token }}', {{ mine_id }}, {{ brigade.brigade_id }}, '10')">
                    <div>10</div>
                    <div>{{ brigade.recruit_worker_cost|multiply:10|short_format}}</div>
                </div>
                <div class="small-button">
                    <div>U</div>
                    <div>10k</div>
                </div>
            </div>
        </a>
    {% endfor %}
    {% include 'utils/pagenator.htm' with app='game:brigade' param1=brigades param2=mine_id %}
    <a href="{% url 'game:mine' %}" class="default-button">Шахты</a>
    <a href="{% url 'game:game' %}" class="default-button">Главное меню</a>
{% endblock %}

source/templates/game/game.htm
{% extends "base.htm" %}
{% load static %}

{% block style %}game.css{% endblock %}

{% block content %}
    <h2>Лента событий</h2>
    <div class="infobox">
        {% for action in actions %}
            <p>{{ action.time|date:"d.m.y H:i" }} {% autoescape off %}{{ action.action }} {% endautoescape %}</p>
        {% endfor %}
    </div>
    <div class="linkbox">
        <h2>Общее</h2>
        <a href="{% url 'user:profile' %}" class="default-button">Профиль</a>
        <a href="{% url 'user:logout' %}" class="default-button">Форум</a>
        <a href="{% url 'game:rating' %}" class="default-button">Рейтинги</a>
        <a href="{% url 'user:logout' %}" class="default-button">Магазин</a>
        <h2>Компания</h2>
        <a href="{% url 'game:mine' %}" class="default-button">Шахты</a>
        <a href="{% url 'user:logout' %}" class="default-button">Сотрудники</a>
        <a href="{% url 'user:logout' %}" class="default-button">Профсоюзы</a>
        <a href="{% url 'user:logout' %}" class="default-button">Артефакты</a>
        <h2>Другое</h2>
        <a href="{% url 'user:logout' %}" class="default-button">Новости</a>
        <a href="{% url 'user:logout' %}" class="default-button">Правила</a>
        <a href="{% url 'user:logout' %}" class="default-button">Помощь</a>
    </div>
{% endblock %}

source/templates/game/mine.htm
{% extends "base.htm" %}
{% load static %}
{% load paginator_offset %}
{% load short_format %}
{% load multiply %}

{% block style %}game.css{% endblock %}

{% block content %}
    <h2>Список шахт</h2>
    <a href="#" onclick="mine_request('{{ csrf_token }}', 'build')" class="default-button">Построить шахту ({{ last_price|short_format }})</a>
    {% for mine in mines.data %}
        <div class="mine">
            <a href="{% url 'game:brigade' mine.mine_id %}" class="left">
                <div>
                    <img src="{% static 'images/mines/' %}{{ mine.icon }}" class="icon">
                </div>
                <div>
                    <div>{{ mine.name }}</div>
                    <div class="stats">
                        <img src="{% static 'images/mines/percent.png' %}"><div>{{ mine.percent_income }}</div>
                        <img src="{% static 'images/mines/shovel4.png' %}"><div>{{ mine.depth }}</div>
                        <img src="{% static 'images/mines/income.png' %}"><div>{{ mine.income_percent|short_format }}</div>
                    </div>
                </div>
            </a>
            <div class="right">
                <div class="small-button" onclick="mine_request('{{ csrf_token }}', 'upgrade', '1', {{ mine.id }})">
                    <div>1</div>
                    <div>{{ mine.dig_cost|short_format }}</div>
                </div>
                <div class="small-button" onclick="mine_request('{{ csrf_token }}', 'upgrade', '10', {{ mine.id }})">
                    <div>10</div>
                    <div>{{ mine.dig_cost|multiply:10|short_format }}</div>
                </div>
                <div class="small-button">
                    <div>U</div>
                    <div>10k</div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% include 'utils/pagenator.htm' with app='game:mine' param1=mines %}
    <a href="{% url 'game:game' %}" class="default-button">Главное меню</a>
{% endblock %}

source/templates/game/rating.htm
{% extends "base.htm" %}
{% load static %}
{% load paginator_offset %}
{% load short_format %}

{% block style %}game.css{% endblock %}

{% block content %}
    <h2>Общий</h2>
    {% for page in pages.data %}
        <div class="rating">
            <div>
                {% include 'game/rating/username.htm' %}
            </div>
            <div>
                <img src="{% static 'images/rating.png' %}">{{ page.total|short_format }}
            </div>
        </div>
    {% endfor %}
    {% include 'utils/pagenator.htm' with app='game:rating' param1=pages %}
    {% include 'game/rating/button.htm' %}
{% endblock %}